"""Emit a tex macros file from calibration_baseline/summary.json.

Per CLAUDE.md: every inline number in a paper must resolve through a
script-generated source. This script writes
``results/counter_decode/calibration_baseline/macros.tex``.

Usage: uv run python scripts/build_calibration_baseline_macros.py
"""

from __future__ import annotations

import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
SUMMARY = REPO_ROOT / "results" / "counter_decode" / "calibration_baseline" / "summary.json"
OUT = REPO_ROOT / "results" / "counter_decode" / "calibration_baseline" / "macros.tex"


def main() -> None:
    data = json.loads(SUMMARY.read_text())
    lines: list[str] = [
        "% AUTO-GENERATED by scripts/build_calibration_baseline_macros.py — do not edit by hand.",
    ]

    config = data["config"]
    lines += [
        f"\\newcommand{{\\calNcal}}{{{config['n_calibration']}}}",
        f"\\newcommand{{\\calNtest}}{{{config['n_test']}}}",
        f"\\newcommand{{\\calLength}}{{{config['length']}}}",
        f"\\newcommand{{\\calWarmup}}{{{config['warmup']}}}",
        f"\\newcommand{{\\calSigmaZero}}{{{config['sigma_0']}}}",
        f"\\newcommand{{\\calU}}{{{config['length'] - config['warmup']}}}",
    ]

    name_map = {"wikitext": "WT", "writingprompts": "WP"}
    for corpus, prefix in name_map.items():
        cal = data["calibration"][corpus]
        lines += [
            f"\\newcommand{{\\calLogBetaStreamMed{prefix}}}{{{cal['log_beta_streaming_median']:+.3f}}}",
            f"\\newcommand{{\\calLogBetaStreamPooled{prefix}}}{{{cal['log_beta_streaming_pooled']:+.3f}}}",
            f"\\newcommand{{\\calLogBetaMLE{prefix}}}{{{cal['log_beta_mle']:+.3f}}}",
            f"\\newcommand{{\\calNllOne{prefix}}}{{{cal['nll_at_one_calibration']:.4f}}}",
            f"\\newcommand{{\\calNllMLE{prefix}}}{{{cal['nll_at_mle_calibration']:.4f}}}",
            f"\\newcommand{{\\calConsistencyGap{prefix}}}{{{cal['consistency_gap_pooled_vs_mle']:+.3f}}}",
        ]

    for corpus, prefix in name_map.items():
        test = data["test"][corpus]
        # Test PPL at each labeled β.
        for i, label in enumerate(test["beta_labels"]):
            ppl = test["per_token_ppl_mean"][i]
            dlp = test["delta_log_ppl_mean"][i]
            t = test["paired_t_vs_T1"][i]
            p = test["paired_p_vs_T1"][i]
            safe_label = "".join(c for c in label if c.isalnum())
            lines += [
                f"\\newcommand{{\\calTestPPL{prefix}{safe_label}}}{{{ppl:.3f}}}",
                f"\\newcommand{{\\calTestDeltaLogPPL{prefix}{safe_label}}}{{{dlp:+.4f}}}",
                f"\\newcommand{{\\calTestTStat{prefix}{safe_label}}}{{{t:+.2f}}}",
                f"\\newcommand{{\\calTestPVal{prefix}{safe_label}}}{{{p:.3g}}}",
            ]

    OUT.write_text("\n".join(lines) + "\n")
    print(f"[macros-cal] wrote {OUT}")


if __name__ == "__main__":
    main()
