#!/usr/bin/env python3
"""Build script-generated LaTeX for the compiled tech report.

Reads the authoritative ``summary.json`` files produced by the individual
experiments and emits, under ``results/tables/``:

  * ``paper_macros.tex``      -- one ``\\newcommand`` per inline scalar cited
                                 in the paper's prose.
  * ``tab_*.tex``             -- tabular *bodies* (the ``\\begin{tabular}`` ...
                                 ``\\end{tabular}`` block only) for every
                                 multi-row table imported into the paper.

Nothing here is hand-typed from memory: every number resolves to a field in a
JSON file under ``results/``.  The paper ``\\input``s these outputs; prose
references macros, tables ``\\input`` the bodies.  This is the citation analog
of the ``import-content`` discipline.

Re-run after any experiment is re-run:

    uv run python scripts/build_paper_macros.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
CD = ROOT / "results" / "counter_decode"
TABLES = ROOT / "results" / "tables"
OUT_DIR = TABLES


def load(path: Path) -> Any:
    if not path.is_file():
        raise FileNotFoundError(f"required data source missing: {path}")
    with path.open() as fh:
        return json.load(fh)


# ---------------------------------------------------------------------------
# formatting helpers
# ---------------------------------------------------------------------------
def f(x: float, nd: int = 3) -> str:
    """Plain fixed-point."""
    return f"{x:.{nd}f}"


def sgn(x: float, nd: int = 3) -> str:
    """Signed fixed-point (always shows + or -), matching the reports."""
    return f"{x:+.{nd}f}"


def sci(x: float) -> str:
    """Scientific notation for the ~0 corrected closed-loop errors."""
    return f"{x:.1e}".replace("e-0", "e{-}").replace("e+0", "e{+}")


# ---------------------------------------------------------------------------
# load every authoritative source
# ---------------------------------------------------------------------------
src = {
    "f0": load(CD / "tables" / "F0_summary.json"),
    "f12": load(CD / "tables" / "F1.2_summary.json"),
    "f3": load(CD / "tables" / "F3_summary.json"),
    "svd": load(CD / "tables" / "F1_F2_svd_summary.json"),
    "blacklist": load(TABLES / "blacklist_summary.json"),
    "topk": load(TABLES / "topk_summary_L2048.json"),
    "expb": load(CD / "sliding_filter_mixed" / "summary.json"),
    "expc": load(CD / "entropy_probe" / "summary.json"),
    "expc_swap": load(CD / "entropy_probe" / "swap_summary.json"),
    "bsweep": load(CD / "belief_sweep" / "summary.json"),
    "binv": load(CD / "belief_invariance" / "summary.json"),
}

PROV = (
    "% AUTO-GENERATED by scripts/build_paper_macros.py -- do not edit by hand.\n"
    "% Data sources: results/counter_decode/{tables,sliding_filter_mixed,\n"
    "%   entropy_probe,belief_sweep,belief_invariance}/*.json and\n"
    "%   results/tables/{blacklist,topk}_summary*.json ; plus the\n"
    "%   per-experiment macro files calibration_baseline/macros.tex and\n"
    "%   natural_text/macros.tex (digit-in-name sanitised to a word).\n"
)

# accumulate scalar macros and table bodies
macros: dict[str, str] = {}
bodies: dict[str, str] = {}


def M(name: str, value: str) -> None:
    if name in macros:
        raise ValueError(f"duplicate macro name {name}")
    if not name.isalpha():
        # TeX control-sequence names are letters only; a digit would make
        # \fooBar5 parse as \fooBar followed by literal "5".
        raise ValueError(f"macro name must be letters-only (no digits): {name}")
    macros[name] = value


# ---------------------------------------------------------------------------
# Table: F0 concentration headline (corrected vs uncorrected, late window)
# ---------------------------------------------------------------------------
rows = []
for r in src["f0"]["rows"]:
    rows.append(
        f"{f(r['beta_target'],1)} & {f(r['max_p_sample_corr_late'],3)} & "
        f"{f(r['max_p_sample_unco_late'],3)} & {f(r['entropy_sample_corr_late'],2)} & "
        f"{f(r['entropy_sample_unco_late'],2)} \\\\"
    )
bodies["tab_f0_concentration"] = (
    "\\begin{tabular}{ccccc}\n\\toprule\n"
    "$\\beta^{\\mathrm{target}}$ & "
    "corr.\\ max$P$ & unco.\\ max$P$ & corr.\\ $H$ & unco.\\ $H$ \\\\\n\\midrule\n"
    + "\n".join(rows)
    + "\n\\bottomrule\n\\end{tabular}\n"
)

# Table: F1.2 streaming beta-hat drift under uncorrected decoding
rows = []
for r in src["f12"]["rows"]:
    rows.append(
        f"{f(r['beta_dec'],1)} & {sgn(r['median_log_beta_hat_at_T'],2)} & "
        f"{f(r['iqr_log_beta_hat_at_T'],2)} \\\\"
    )
bodies["tab_f12_drift"] = (
    "\\begin{tabular}{ccc}\n\\toprule\n"
    "$\\beta^{\\mathrm{dec}}$ & median $\\log\\hat\\beta_{t=200}$ & IQR \\\\\n\\midrule\n"
    + "\n".join(rows)
    + "\n\\bottomrule\n\\end{tabular}\n"
)

# Table: F3 closed-loop error E(T)
rows = []
for r in src["f3"]["rows"]:
    rows.append(
        f"{f(r['beta_target'],1)} & ${sci(r['median_abs_log_err_corr_at_T'])}$ & "
        f"{f(r['median_abs_log_err_unco_at_T'],2)} \\\\"
    )
bodies["tab_f3_closedloop"] = (
    "\\begin{tabular}{ccc}\n\\toprule\n"
    "$\\beta^{\\mathrm{target}}$ & $E(T)$ corrected & $E(T)$ uncorrected \\\\\n\\midrule\n"
    + "\n".join(rows)
    + "\n\\bottomrule\n\\end{tabular}\n"
)

# inline F0/F1/F3 scalars
f3_half = next(r for r in src["f3"]["rows"] if r["beta_target"] == 0.5)
M("fzeroEuncoHalf", f(f3_half["median_abs_log_err_unco_at_T"], 2))      # 4.74
f12_half = next(r for r in src["f12"]["rows"] if r["beta_dec"] == 0.5)
M("fzeroLogbhatHalf", sgn(f12_half["median_log_beta_hat_at_T"], 2))      # -4.74
M("fzeroRfinal", f(src["svd"]["rows"][-1]["R"], 2))                      # 0.15
f0_half = next(r for r in src["f0"]["rows"] if r["beta_target"] == 0.5)
M("fzeroMaxPcorrHalf", f(f0_half["max_p_sample_corr_late"], 3))          # 0.579
M("fzeroMaxPuncoHalf", f(f0_half["max_p_sample_unco_late"], 3))          # 0.001

# ---------------------------------------------------------------------------
# Table + scalars: blacklist self-prediction (5 banned ranks)
# CI triplets in the JSON are [point, ci_lo, ci_hi].
# ---------------------------------------------------------------------------
rows = []
for r in src["blacklist"]["per_rank"]:
    lme = r["late_minus_early_within_treatment"]
    tvc = r["treatment_minus_control_at_late"]
    tok = r["decoded"].replace(" ", "\\textvisiblespace ")
    rows.append(
        f"{r['banned_rank']} & \\texttt{{{tok}}} & {sgn(lme[0],3)} & "
        f"{sgn(tvc[0],3)} & $[{f(tvc[1],3)},\\,{f(tvc[2],3)}]$ \\\\"
    )
bodies["tab_blacklist"] = (
    "\\begin{tabular}{clccc}\n\\toprule\n"
    "banned rank & token & $\\Delta p_{\\mathrm{late-early}}$ & "
    "treat.$-$ctrl (late) & 95\\% CI \\\\\n\\midrule\n"
    + "\n".join(rows)
    + "\n\\bottomrule\n\\end{tabular}\n"
)
bl1 = src["blacklist"]["per_rank"][0]
M("blRankOneDeltaP", sgn(bl1["late_minus_early_within_treatment"][0], 3))   # -0.018
M("blRankOneTvc", sgn(bl1["treatment_minus_control_at_late"][0], 3))        # -0.016
M("blRankOneTvcLo", f(bl1["treatment_minus_control_at_late"][1], 3))        # -0.019
M("blRankOneTvcHi", f(bl1["treatment_minus_control_at_late"][2], 3))        # -0.013

# ---------------------------------------------------------------------------
# Table + scalars: top-k self-prediction (cliff at rank K)
# ---------------------------------------------------------------------------
rows = []
for h in src["topk"]["h3"]:
    da = h["delta_at"]
    rows.append(
        f"{h['K']} & {sgn(da[0],3)} & $[{f(da[1],3)},\\,{f(da[2],3)}]$ \\\\"
    )
bodies["tab_topk"] = (
    "\\begin{tabular}{ccc}\n\\toprule\n"
    "$k$ & treat.$-$ctrl at rank $K$ & 95\\% CI \\\\\n\\midrule\n"
    + "\n".join(rows)
    + "\n\\bottomrule\n\\end{tabular}\n"
)
tk = {str(h["K"]): h["delta_at"] for h in src["topk"]["h3"]}
M("tkDeltaKthree", sgn(tk["3"][0], 3))   # +0.475
M("tkDeltaKfive", sgn(tk["5"][0], 3))    # +0.170

# ---------------------------------------------------------------------------
# Table + scalars: Exp B sliding beta-hat on alternating genre
# ---------------------------------------------------------------------------
rows = []
for g in src["expb"]["config"]["gammas"]:
    d = src["expb"]["per_gamma"][str(g)]
    rows.append(
        f"{f(g,2)} & {sgn(d['wt_log_beta_mean'],3)} & {sgn(d['wp_log_beta_mean'],3)} & "
        f"{sgn(d['wt_log_beta_minus_wp_log_beta'],3)} & {f(d['wt_H_mean'],3)} & "
        f"{f(d['wp_H_mean'],3)} \\\\"
    )
bodies["tab_expb_genre"] = (
    "\\begin{tabular}{cccccc}\n\\toprule\n"
    "$\\gamma$ & $\\log\\hat\\beta$ wiki & $\\log\\hat\\beta$ WP & WT$-$WP & "
    "$H$ wiki & $H$ WP \\\\\n\\midrule\n"
    + "\n".join(rows)
    + "\n\\bottomrule\n\\end{tabular}\n"
)
g090 = src["expb"]["per_gamma"]["0.9"]
g100 = src["expb"]["per_gamma"]["1.0"]
M("expbGenreGap", sgn(g090["wt_log_beta_minus_wp_log_beta"], 3))   # +0.054
M("expbHwiki", f(g090["wt_H_mean"], 3))                            # 1.686
M("expbHwp", f(g090["wp_H_mean"], 3))                              # 3.024
M("expbEntropyGap", f(g090["wp_H_mean"] - g090["wt_H_mean"], 2))   # 1.34
M("expbSaturated", sgn(g100["wt_log_beta_mean"], 2))               # -0.46

# ---------------------------------------------------------------------------
# Table + scalars: Exp C late-window pre-decoding entropy
# ---------------------------------------------------------------------------
bd = src["expc"]["by_beta_dec"]
pd = src["expc"]["paired_diffs"]


def hcell(key: str) -> str:
    d = bd[key]
    return f"${f(d['late_entropy_mean_over_prompts'],3)} \\pm {f(d['late_entropy_se_over_prompts'],3)}$"


diff05 = pd["H_betadec_0.5_minus_2.0"]
diff10 = pd["H_betadec_1.0_minus_2.0"]
rows = [
    f"$\\beta_{{\\mathrm{{dec}}}}=0.5$ & {hcell('0.5')} & "
    f"${sgn(diff05['mean'],3)} \\pm {f(diff05['se'],3)}$ "
    f"($t={sgn(diff05['t_stat'],1)}$, $n_+={diff05['n_positive']}/{diff05['n_prompts']}$) \\\\",
    f"$\\beta_{{\\mathrm{{dec}}}}=1.0$ & {hcell('1.0')} & ${sgn(diff10['mean'],3)}$ \\\\",
    f"$\\beta_{{\\mathrm{{dec}}}}=2.0$ & {hcell('2.0')} & --- \\\\",
]
bodies["tab_expc_late"] = (
    "\\begin{tabular}{lcc}\n\\toprule\n"
    "condition & late-window $H$ (nats) & paired diff vs $\\beta=2.0$ \\\\\n\\midrule\n"
    + "\n".join(rows)
    + "\n\\bottomrule\n\\end{tabular}\n"
)
M("expcLateHalf", f(bd["0.5"]["late_entropy_mean_over_prompts"], 3))   # 9.216
M("expcLateTwo", f(bd["2.0"]["late_entropy_mean_over_prompts"], 3))    # 1.172
M("expcSpread", f(diff05["mean"], 2))                                  # 8.04
M("expcSpreadT", sgn(diff05["t_stat"], 1))                            # +69.7

# ---------------------------------------------------------------------------
# Table + scalars: Exp C swap-prefix control
# ---------------------------------------------------------------------------
label = {
    "pre05_post05": "$0.5 \\to 0.5$ (control)",
    "pre05_post10": "$0.5 \\to 1.0$",
    "pre05_post20": "$0.5 \\to 2.0$",
    "pre20_post05": "$2.0 \\to 0.5$",
    "pre20_post20": "$2.0 \\to 2.0$ (control)",
}
rows = []
order = ["pre05_post05", "pre05_post10", "pre05_post20", "pre20_post05", "pre20_post20"]
for k in order:
    v = src["expc_swap"]["post_switch_trajectory"][k]
    pre = src["expc_swap"]["pre_switch_means"][k]["median_H_pre"]
    offs = v["median_H_post_step_0_5_10_20_50"]
    cells = " & ".join(f(x, 2) for x in offs)
    cond = k.replace("_", "\\_")
    rows.append(f"\\texttt{{{cond}}} & {label[k]} & {f(pre,2)} & {cells} \\\\")
bodies["tab_expc_swap"] = (
    "\\begin{tabular}{llcrrrrr}\n\\toprule\n"
    "condition & $\\beta_{\\mathrm{pre}}\\!\\to\\!\\beta_{\\mathrm{post}}$ & "
    "pre-med & $+0$ & $+5$ & $+10$ & $+20$ & $+50$ \\\\\n\\midrule\n"
    + "\n".join(rows)
    + "\n\\bottomrule\n\\end{tabular}\n"
)
sw = src["expc_swap"]
p10 = sw["post_switch_trajectory"]["pre05_post10"]
M("expcSwapPre", f(sw["pre_switch_means"]["pre05_post10"]["median_H_pre"], 2))  # 8.56
M("expcSwapPostFifty", f(p10["median_H_post_step_0_5_10_20_50"][-1], 2))       # 8.91/8.92
M("expcSwitchStep", str(sw["config"]["switch_step"]))                          # 80

# ---------------------------------------------------------------------------
# Table + scalars: belief_sweep closed-loop (top 5 by badness)
# ---------------------------------------------------------------------------
top = src["bsweep"]["top_configs"][:5]
rows = []
for c in top:
    H = c["H_by_bt"]
    Mb = c["M_by_bt"]
    rows.append(
        f"{f(c['gamma'],2)} & {f(c['alpha'],2)} & {f(c['p'],2)} & "
        f"{f(H['0.5'],2)} & {f(H['1.0'],2)} & {f(H['2.0'],2)} & "
        f"{f(Mb['0.5'],2)} & {f(Mb['1.0'],2)} & {f(Mb['2.0'],2)} & "
        f"{f(c['badness'],3)} \\\\"
    )
bodies["tab_bsweep_closed"] = (
    "\\begin{tabular}{cccccccccc}\n\\toprule\n"
    "$\\gamma$ & $\\alpha$ & $p$ & $H$@0.5 & $H$@1 & $H$@2 & "
    "$M$@0.5 & $M$@1 & $M$@2 & badness \\\\\n\\midrule\n"
    + "\n".join(rows)
    + "\n\\bottomrule\n\\end{tabular}\n"
)
M("bsweepBestBadness", f(top[0]["badness"], 3))   # 0.011

# ---------------------------------------------------------------------------
# Table + scalars: belief_invariance (top 5; collapse identical p=0 group)
# ---------------------------------------------------------------------------
tc = src["binv"]["top_configs"]
inv_rows = []
seen_p0 = False
for c in tc:
    ce = c["mean_ce_per_prefix"]
    if c["p"] == 0.0:
        if seen_p0:
            continue  # all p=0 configs are identical (correction off); show one row
        seen_p0 = True
        gcol, acol = "\\textit{any}", "\\textit{any}"
    else:
        gcol, acol = f(c["gamma"], 2), f(c["alpha"], 2)
    inv_rows.append(
        f"{gcol} & {acol} & {f(c['p'],2)} & {f(ce['0.5'],3)} & "
        f"{f(ce['1.0'],3)} & {f(ce['2.0'],3)} \\\\"
    )
    if len(inv_rows) == 5:
        break
bodies["tab_binv_invariance"] = (
    "\\begin{tabular}{cccccc}\n\\toprule\n"
    "$\\gamma$ & $\\alpha$ & $p$ & CE@$\\beta^{\\mathrm{pre}}$=0.5 & CE@1 & CE@2 \\\\\n"
    "\\midrule\n"
    + "\n".join(inv_rows)
    + "\n\\bottomrule\n\\end{tabular}\n"
)
# CE floor (correction off) and the gamma=1, p=1 catastrophe
recs = src["binv"]["records"]
p0_rec = next(r for r in recs if r["p"] == 0.0)
g1p1 = next(r for r in recs if r["gamma"] == 1.0 and r["alpha"] == 1.0 and r["p"] == 1.0)
M("binvCeFloor", f(p0_rec["mean_ce_per_prefix"]["0.5"], 2))     # 3.60
M("binvCeExplode", f(g1p1["mean_ce_per_prefix"]["0.5"], 2))     # 19.44
M("binvVarFloor", f(p0_rec["mean_var_across_prefix"], 3))       # 0.017
M("binvSigmaZero", f(src["binv"]["config"]["sigma_0"], 1))     # 0.2
# the smallest gamma<1 worst-case variance cap quoted as "<= 0.07"
gamma_lt1_vars = [r["mean_var_across_prefix"] for r in recs if r["gamma"] < 1.0]
M("binvVarCap", f(max(gamma_lt1_vars), 2))                      # 0.07

# ---------------------------------------------------------------------------
# Ingest the per-experiment macro files generated by the report build scripts
# (Exp A calibration baseline, natural-text filter). These are themselves
# authoritative (script-generated from JSON); we re-emit them into the single
# paper macro file, sanitising any digit in a macro NAME to a word so that TeX
# does not split e.g. \calTestPPLWTT1 into \calTestPPLWTT + "1".
# ---------------------------------------------------------------------------
_DIGIT_WORD = {
    "0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
    "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine",
}
_NEWCMD_RE = re.compile(r"^\\newcommand\{\\([A-Za-z0-9]+)\}\{(.*)\}\s*$")


def sanitize_name(name: str) -> str:
    return "".join(_DIGIT_WORD.get(c, c) for c in name)


def ingest(path: Path) -> int:
    n = 0
    for line in path.read_text().splitlines():
        m = _NEWCMD_RE.match(line)
        if m:
            M(sanitize_name(m.group(1)), m.group(2))
            n += 1
    return n


n_cal = ingest(CD / "calibration_baseline" / "macros.tex")
n_ntf = ingest(CD / "natural_text" / "macros.tex")
n_sc = ingest(CD / "self_calibration" / "macros.tex")
n_sv = ingest(CD / "self_calibration" / "survey_macros.tex")
# NOTE: data/grid_certificate/macros.tex is NOT ingested here -- the paper
# \input{}s it directly, because its source (results.json) is tracked while
# this script's other sources are regeneratable-only and absent in worktrees.

# ---------------------------------------------------------------------------
# write outputs
# ---------------------------------------------------------------------------
OUT_DIR.mkdir(parents=True, exist_ok=True)

macro_lines = [PROV]
for name in sorted(macros):
    macro_lines.append(f"\\newcommand{{\\{name}}}{{{macros[name]}}}")
(OUT_DIR / "paper_macros.tex").write_text("\n".join(macro_lines) + "\n")

for name, body in bodies.items():
    (OUT_DIR / f"{name}.tex").write_text(
        f"% AUTO-GENERATED by scripts/build_paper_macros.py -- do not edit by hand.\n"
        + body
    )

print(f"wrote paper_macros.tex with {len(macros)} macros "
      f"({n_cal} ingested from calibration_baseline, {n_ntf} from natural_text, "
      f"{n_sc} from self_calibration, {n_sv} from survey)")
print(f"wrote {len(bodies)} table bodies: {', '.join(sorted(bodies))}")
