"""Emit a tex macros file from natural_text/summary.json.

Per the CLAUDE.md discipline: every number in paper prose must resolve through a
script-generated source. This script reads the experiment's summary JSON and
emits ``results/counter_decode/natural_text/macros.tex`` containing one
``\\newcommand`` per inline scalar referenced in the findings document.

Usage:
    uv run python scripts/build_natural_text_macros.py
"""

from __future__ import annotations

import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
SUMMARY = REPO_ROOT / "results" / "counter_decode" / "natural_text" / "summary.json"
OUT = REPO_ROOT / "results" / "counter_decode" / "natural_text" / "macros.tex"


def _safe(macro_name: str) -> str:
    """LaTeX macro names: letters only."""
    return "".join(c for c in macro_name if c.isalpha())


def main() -> None:
    data = json.loads(SUMMARY.read_text())
    lines: list[str] = [
        "% AUTO-GENERATED by scripts/build_natural_text_macros.py — do not edit by hand.",
    ]
    # Per-condition macros: corpus + arm → macro prefix.
    name_map = {
        ("wikitext", "self_gen"): "WikiSelf",
        ("wikitext", "natural"): "WikiNat",
        ("writingprompts", "self_gen"): "WPSelf",
        ("writingprompts", "natural"): "WPNat",
    }
    for row in data["rows"]:
        prefix = name_map[(row["corpus"], row["arm"])]
        lines.append(
            f"\\newcommand{{\\logBetaFinalMed{prefix}}}{{{row['log_beta_final_median']:+.3f}}}"
        )
        lines.append(
            f"\\newcommand{{\\logBetaFinalIqrLow{prefix}}}{{{row['log_beta_final_iqr_low']:+.3f}}}"
        )
        lines.append(
            f"\\newcommand{{\\logBetaFinalIqrHigh{prefix}}}{{{row['log_beta_final_iqr_high']:+.3f}}}"
        )
        lines.append(
            f"\\newcommand{{\\logBetaFinalSe{prefix}}}{{{row['log_beta_final_se_median']:.3f}}}"
        )
        lines.append(
            f"\\newcommand{{\\logBetaFinalT{prefix}}}{{{row['median_t_stat_vs_zero']:+.2f}}}"
        )
        lines.append(
            f"\\newcommand{{\\logBetaFinalTrimMed{prefix}}}{{{row['log_beta_final_trimmed_median']:+.3f}}}"
        )
        lines.append(
            f"\\newcommand{{\\meanEntropy{prefix}}}{{{row['mean_model_entropy_median']:.3f}}}"
        )
        lines.append(
            f"\\newcommand{{\\totalFisher{prefix}}}{{{row['total_fisher_median']:.0f}}}"
        )
        lines.append(
            f"\\newcommand{{\\nPassages{prefix}}}{{{row['n_passages']}}}"
        )
    # Paired natural − self_gen differences.
    paired = data["paired_natural_minus_self_gen"]
    for corpus, key in (("wikitext", "Wiki"), ("writingprompts", "WP")):
        p = paired[corpus]
        lines.append(f"\\newcommand{{\\pairedMeanDiff{key}}}{{{p['mean_diff']:+.3f}}}")
        lines.append(f"\\newcommand{{\\pairedMedianDiff{key}}}{{{p['median_diff']:+.3f}}}")
        lines.append(f"\\newcommand{{\\pairedSeDiff{key}}}{{{p['se_diff']:.3f}}}")
        lines.append(f"\\newcommand{{\\pairedTStat{key}}}{{{p['t_stat']:+.2f}}}")
    # Global params.
    lines.append(f"\\newcommand{{\\sigmaZero}}{{{data['sigma_0']}}}")
    lines.append(f"\\newcommand{{\\priorMode}}{{{-0.5 * data['sigma_0']**2:+.3f}}}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"[macros] wrote {OUT}")


if __name__ == "__main__":
    main()
