"""Emit tex macros + a table body from self_calibration/survey.json (Part 0).

Reads the calibration survey (per-text-type global-T NLL gain) and writes:
  - results/counter_decode/self_calibration/survey_macros.tex  (scalar \\newcommands, scSurv*)
  - results/tables/self_calibration_survey.tex                  (a booktabs tabular)

Macro names use the scSurv<Label> form (letters only) so they pass the paper-macro
guard and the build_paper_macros ingester unchanged.

Usage: uv run python scripts/build_survey_macros.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SUMMARY = REPO_ROOT / "results" / "counter_decode" / "self_calibration" / "survey.json"
MACRO_OUT = REPO_ROOT / "results" / "counter_decode" / "self_calibration" / "survey_macros.tex"
TABLE_OUT = REPO_ROOT / "results" / "tables" / "self_calibration_survey.tex"

# dataset key -> (CamelCase macro label [letters only], pretty table name)
META = {
    "wikitext": ("Wikitext", "WikiText"),
    "writingprompts": ("Writingprompts", "WritingPrompts"),
    "gutenberg": ("Gutenberg", "Gutenberg (archaic EN)"),
    "esperanto": ("Esperanto", "Esperanto"),
    "yoruba": ("Yoruba", "Yoruba"),
    "telugu": ("Telugu", "Telugu"),
    "abc_music": ("AbcMusic", "ABC music"),
    "recaman": ("Recaman", "Recam\\'an (A005132)"),
    "shuffled_wikitext": ("ShuffledWikitext", "shuffled WikiText"),
}


def main() -> None:
    data = json.loads(SUMMARY.read_text())
    by = data["by_dataset"]
    cfg = data["config"]
    lines = [
        "% AUTO-GENERATED by scripts/build_survey_macros.py — do not edit by hand.",
        f"\\newcommand{{\\scSurvNtrain}}{{{cfg['n_train']}}}",
        f"\\newcommand{{\\scSurvNtest}}{{{cfg['n_test']}}}",
        f"\\newcommand{{\\scSurvLength}}{{{cfg['length']}}}",
        f"\\newcommand{{\\scSurvNDatasets}}{{{len(by)}}}",
    ]
    max_optT = 0.0
    for key, d in by.items():
        if key not in META:
            continue
        lab = META[key][0]
        lines += [
            f"\\newcommand{{\\scSurvOptT{lab}}}{{{d['optimal_T']:.2f}}}",
            f"\\newcommand{{\\scSurvGain{lab}}}{{{d['global_T_gain_nats']:+.4f}}}",
            f"\\newcommand{{\\scSurvGainT{lab}}}{{{d['gain_t']:+.1f}}}",
            f"\\newcommand{{\\scSurvGainP{lab}}}{{{d['gain_p']:.2g}}}",
            f"\\newcommand{{\\scSurvNllBetaOne{lab}}}{{{d['nll_beta1_mean']:.3f}}}",
            f"\\newcommand{{\\scSurvEntropy{lab}}}{{{d['mean_beta1_entropy_nats']:.2f}}}",
        ]
        max_optT = max(max_optT, d["optimal_T"])
    lines.append(f"\\newcommand{{\\scSurvMaxOptT}}{{{max_optT:.2f}}}")

    MACRO_OUT.write_text("\n".join(lines) + "\n")

    rows = []
    for key in data.get("ranked_by_gain", list(by.keys())):
        if key not in META:
            continue
        d = by[key]
        pretty = META[key][1]
        sig = "" if d["gain_p"] >= 0.05 else ("$^{*}$" if d["gain_p"] >= 1e-3 else "$^{**}$")
        rows.append(
            f"{pretty} & {d['optimal_T']:.2f} & {d['global_T_gain_nats']:+.4f}{sig} & "
            f"{d['nll_beta1_mean']:.2f} & {d['mean_beta1_entropy_nats']:.2f} \\\\"
        )
    table = [
        "% AUTO-GENERATED by scripts/build_survey_macros.py — do not edit by hand.",
        "\\begin{tabular}{lcccc}",
        "\\toprule",
        "text type & optimal $T$ & $\\Delta$NLL vs $\\beta{=}1$ (nats) & $\\beta{=}1$ NLL & $H_{\\beta=1}$ \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
    ]
    TABLE_OUT.write_text("\n".join(table) + "\n")
    print(f"[survey-macros] wrote {MACRO_OUT}")
    print(f"[survey-macros] wrote {TABLE_OUT}")


if __name__ == "__main__":
    main()
