"""Emit tex macros + a table body from self_calibration/recovery.json (Part 1).

Per CLAUDE.md: every inline number in the paper resolves through a
script-generated source. Writes:
  - results/counter_decode/self_calibration/macros.tex   (scalar \\newcommands)
  - results/tables/self_calibration_recovery.tex          (a booktabs tabular)

Temperature labels are spelled out (0.5 -> ZeroFive, ...) so macro names carry
no digits and pass through build_paper_macros unchanged.

Usage: uv run python scripts/build_self_calibration_macros.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SUMMARY = REPO_ROOT / "results" / "counter_decode" / "self_calibration" / "recovery.json"
MACRO_OUT = REPO_ROOT / "results" / "counter_decode" / "self_calibration" / "macros.tex"
TABLE_OUT = REPO_ROOT / "results" / "tables" / "self_calibration_recovery.tex"

# T (json key) -> digit-free macro-name label.
T_LABEL = {"0.5": "ZeroFive", "0.7": "ZeroSeven", "1.0": "One", "1.5": "OneFive", "2.0": "Two"}


def main() -> None:
    data = json.loads(SUMMARY.read_text())
    cfg = data["config"]
    lines: list[str] = [
        "% AUTO-GENERATED by scripts/build_self_calibration_macros.py — do not edit by hand.",
        f"\\newcommand{{\\scNseq}}{{{cfg['n_seq']}}}",
        f"\\newcommand{{\\scSeedLen}}{{{cfg['seed_len']}}}",
        f"\\newcommand{{\\scLength}}{{{cfg['length']}}}",
        f"\\newcommand{{\\scGenLen}}{{{cfg['gen_len']}}}",
        f"\\newcommand{{\\scWarmup}}{{{cfg['warmup']}}}",
        f"\\newcommand{{\\scSigmaZero}}{{{cfg['sigma_0']}}}",
    ]

    rows: list[str] = []
    for Tkey, lab in T_LABEL.items():
        if Tkey not in data["by_temp"]:
            continue
        r = data["by_temp"][Tkey]
        rec = r["recovery"]
        pn = r["prediction_nll_nats"]
        diag = r["diagnostics"]
        gain = -pn["faithful_minus_beta1"]["mean"]      # +nats = improvement over β=1
        gain_t = pn["faithful_minus_beta1"]["t"]
        oracle_gap = pn["faithful_minus_oracle"]["mean"]
        lines += [
            f"\\newcommand{{\\scBetaTrue{lab}}}{{{r['beta_true']:.3f}}}",
            f"\\newcommand{{\\scLogBetaTrue{lab}}}{{{r['log_beta_true']:+.3f}}}",
            f"\\newcommand{{\\scFaithSettled{lab}}}{{{rec['faithful_settled_logbeta_mean']:+.3f}}}",
            f"\\newcommand{{\\scFaithBias{lab}}}{{{rec['faithful_settled_bias_vs_true']:+.3f}}}",
            f"\\newcommand{{\\scOrigSettled{lab}}}{{{rec['original_settled_logbeta_mean']:+.3f}}}",
            f"\\newcommand{{\\scOrigBias{lab}}}{{{rec['original_settled_bias_vs_true']:+.3f}}}",
            f"\\newcommand{{\\scMleBeta{lab}}}{{{r['sanity_pooled_mle_beta']:.3f}}}",
            f"\\newcommand{{\\scNllBetaOne{lab}}}{{{pn['beta1_mean']:.3f}}}",
            f"\\newcommand{{\\scNllFaith{lab}}}{{{pn['adaptive_faithful_mean']:.3f}}}",
            f"\\newcommand{{\\scNllOracle{lab}}}{{{pn['oracle_1overT_mean']:.3f}}}",
            f"\\newcommand{{\\scNllGain{lab}}}{{{gain:.3f}}}",
            f"\\newcommand{{\\scNllGainT{lab}}}{{{gain_t:+.1f}}}",
            f"\\newcommand{{\\scOracleGap{lab}}}{{{oracle_gap:+.3f}}}",
            f"\\newcommand{{\\scGenEntropy{lab}}}{{{diag['gen_dist_entropy_nats']:.2f}}}",
            f"\\newcommand{{\\scDistinct{lab}}}{{{diag['distinct_token_ratio']:.2f}}}",
        ]
        coherent = "yes" if diag["gen_dist_entropy_nats"] < 3.0 else "near-random"
        rows.append(
            f"{Tkey} & {r['beta_true']:.2f} & "
            f"{rec['faithful_settled_logbeta_mean']:+.2f}\\,({rec['faithful_settled_bias_vs_true']:+.2f}) & "
            f"{rec['original_settled_logbeta_mean']:+.2f}\\,({rec['original_settled_bias_vs_true']:+.2f}) & "
            f"{gain:+.2f} & {oracle_gap:+.3f} & {diag['gen_dist_entropy_nats']:.2f} \\\\"
        )

    MACRO_OUT.write_text("\n".join(lines) + "\n")

    table = [
        "% AUTO-GENERATED by scripts/build_self_calibration_macros.py — do not edit by hand.",
        "\\begin{tabular}{ccccccc}",
        "\\toprule",
        "$T$ & $\\beta{=}1/T$ & faithful $\\log\\hat\\beta$ (bias) & original $\\log\\hat\\beta$ (bias) "
        "& $\\Delta$NLL vs $\\beta{=}1$ & oracle gap & gen.\\ $H$ \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
    ]
    TABLE_OUT.write_text("\n".join(table) + "\n")
    print(f"[macros-selfcal] wrote {MACRO_OUT}")
    print(f"[macros-selfcal] wrote {TABLE_OUT}")


if __name__ == "__main__":
    main()
