"""Generate the grid-certificate results table for the paper.

Reads data/grid_certificate/results.json (written by
scripts/grid_certificate_experiments.py analyze) and writes
results/tables/tab_grid_certificate.tex plus data/grid_certificate/macros.tex
(ingested into paper_macros.tex by scripts/build_paper_macros.py). Numbers
reach the paper only through this script, never by hand (import-content
discipline).
"""

from __future__ import annotations

import json
import pathlib

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
RESULTS_JSON = REPO_ROOT / "data" / "grid_certificate" / "results.json"
OUT_TEX = REPO_ROOT / "results" / "tables" / "tab_grid_certificate.tex"
OUT_MACROS = REPO_ROOT / "data" / "grid_certificate" / "macros.tex"


def _fmt_p(p: float) -> str:
    if p >= 0.01:
        return f"$p={p:.2f}$"
    exponent = int(f"{p:.0e}".split("e")[1])
    return f"$p<10^{{{exponent + 1}}}$"


def main() -> None:
    r = json.loads(RESULTS_JSON.read_text())
    h1, h2, h3, h4 = r["H1"], r["H2"], r["H3"], r["H4"]

    rows = [
        (
            "H1 coverage (synthetic, well-spec.)",
            f"{h1['covered']}/{h1['n']} cover the MLE",
            _fmt_p(h1["p_value"]),
            "fails" if h1["fails"] else "passes",
        ),
        (
            "H2 non-vacuousness (Qwen, $\\beta{=}1$)",
            f"median width {h2['median_width']:.2f} ($<{0.2}$ in $\\log\\beta$)",
            _fmt_p(h2["p_value"]),
            "holds" if h2["holds"] else "does not hold",
        ),
        (
            "H3 degradation (peaked vs.\\ natural)",
            f"median {h3['median_peaked']:.2f} vs.\\ {h3['median_natural']:.2f}",
            _fmt_p(h3["p_value"]),
            "holds" if h3["holds"] else "does not hold",
        ),
        (
            "H4 transfer (faithful Laplace in bar)",
            f"{h4['agree']}/{h4['n']} inside",
            _fmt_p(h4["p_value"]),
            "fails" if h4["fails"] else "passes",
        ),
    ]
    lines = [
        "% AUTO-GENERATED by scripts/build_grid_certificate_table.py -- do not edit by hand.",
        "\\begin{tabular}{llll}",
        "\\toprule",
        "pre-registered hypothesis & outcome & test & verdict \\\\",
        "\\midrule",
    ]
    for name, outcome, p, verdict in rows:
        lines.append(f"{name} & {outcome} & {p} & {verdict} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    OUT_TEX.write_text("\n".join(lines))
    print(f"wrote {OUT_TEX}")

    expl = r["exploratory"]
    macros = {
        "gridCertCoverage": f"{h1['covered']}/{h1['n']}",
        "gridCertMedianWidthBtOne": f"{h2['median_width']:.2f}",
        "gridCertFaithfulAgree": f"{h4['agree']}/{h4['n']}",
        "gridCertOriginalAgree": expl["original_laplace_agreement"],
    }
    macro_lines = [
        "% AUTO-GENERATED by scripts/build_grid_certificate_table.py -- do not edit by hand."
    ]
    for name, value in sorted(macros.items()):
        macro_lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")
    OUT_MACROS.write_text("\n".join(macro_lines) + "\n")
    print(f"wrote {OUT_MACROS} with {len(macros)} macros")


if __name__ == "__main__":
    main()
