"""Emit LaTeX macros from a go/no-go summary.json (numbers-from-scripts).

Every inline number in the findings write-up must come from here, never hand-typed
(repo rule). Usage:
    uv run python scripts/build_full_sequence_macros.py <summary.json> <out_macros.tex>
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def _esc_tag(s: str) -> str:
    """Make a string safe for a LaTeX macro name (letters only)."""
    digits = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
              "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine",
              ".": "p", "-": "neg", "_": ""}
    out = []
    for ch in s:
        if ch.isalpha():
            out.append(ch)
        elif ch in digits:
            out.append(digits[ch])
    return "".join(out)


def main() -> None:
    summary_path, out_path = sys.argv[1], sys.argv[2]
    s = json.load(open(summary_path))
    lines: list[str] = [
        "% Auto-generated by scripts/build_full_sequence_macros.py — do not edit by hand.",
        f"\\newcommand{{\\fsModel}}{{{s['model'].replace('_', '-')}}}",
        f"\\newcommand{{\\fsNRecords}}{{{s['n_records_total']}}}",
    ]

    def emit(prefix: str, block: dict) -> None:
        for T, m in block.items():
            tag = _esc_tag(T)
            lines.append(f"\\newcommand{{\\fs{prefix}{tag}Npos}}{{{m['n_positions']}}}")
            lines.append(f"\\newcommand{{\\fs{prefix}{tag}Dtot}}{{{m['D_total_nats']:.4f}}}")
            lines.append(f"\\newcommand{{\\fs{prefix}{tag}DtotLo}}{{{m['D_total_ci'][0]:.4f}}}")
            lines.append(f"\\newcommand{{\\fs{prefix}{tag}DtotHi}}{{{m['D_total_ci'][2]:.4f}}}")
            lines.append(f"\\newcommand{{\\fs{prefix}{tag}FracBestT}}{{{m['frac_bestT']:.3f}}}")
            lines.append(f"\\newcommand{{\\fs{prefix}{tag}FracFiltLin}}{{{m['frac_filter_linear']:.3f}}}")
            lines.append(f"\\newcommand{{\\fs{prefix}{tag}FracFiltCV}}{{{m['frac_filter_cv']:.3f}}}")
            lines.append(f"\\newcommand{{\\fs{prefix}{tag}FracLogitCV}}{{{m['frac_logit_cv']:.3f}}}")
            fmb = m['frac_filter_cv_minus_bestT']
            lmb = m['frac_logit_cv_minus_bestT']
            lines.append(f"\\newcommand{{\\fs{prefix}{tag}FiltCVMinusBestTLo}}{{{fmb[0]:.3f}}}")
            lines.append(f"\\newcommand{{\\fs{prefix}{tag}FiltCVMinusBestTPt}}{{{fmb[1]:.3f}}}")
            lines.append(f"\\newcommand{{\\fs{prefix}{tag}FiltCVMinusBestTHi}}{{{fmb[2]:.3f}}}")
            lines.append(f"\\newcommand{{\\fs{prefix}{tag}LogitCVMinusBestTLo}}{{{lmb[0]:.3f}}}")
            lines.append(f"\\newcommand{{\\fs{prefix}{tag}LogitCVMinusBestTPt}}{{{lmb[1]:.3f}}}")
            lines.append(f"\\newcommand{{\\fs{prefix}{tag}LogitCVMinusBestTHi}}{{{lmb[2]:.3f}}}")
            lines.append(f"\\newcommand{{\\fs{prefix}{tag}AffRes}}{{{m['affine_residual_fraction_mean']:.3f}}}")
            lines.append(f"\\newcommand{{\\fs{prefix}{tag}WHat}}{{{m['w_hat']:.3f}}}")
            lines.append(f"\\newcommand{{\\fs{prefix}{tag}Cov}}{{{m['covered_mass_mean']:.4f}}}")

    emit("Overall", s["overall"])
    dec = s.get("decision_overall", {})
    lines.append(f"\\newcommand{{\\fsAnyGo}}{{{'GO' if dec.get('ANY_GO') else 'NO-GO'}}}")

    Path(out_path).write_text("\n".join(lines) + "\n")
    print(f"WROTE {out_path} ({len(lines)} macros)")


if __name__ == "__main__":
    main()
